version: "3"
services:
  worker:
    build: .
    command: "./monitor worker"
    depends_on:
      - postgres
    networks:
      - monitor
    environment:
      MONITOR_DATABASE_HOST: postgres
      MONITOR_DATABASE_NAME: monitor
      MONITOR_DATABASE_USERNAME: monitor
      MONITOR_DATABASE_PASSWORD: monitor
      MONITOR_DATABASE_PORT: "5432"
      MONITOR_SMTP_USERNAME: "AKIASPX5Y4XF6TWOLHW3"
      MONITOR_SMTP_PASSWORD: "BEr1rnITu3BpGLtACr3EP6BQcKnAKcFTiHYftoys/1QB"
      MONITOR_SMTP_FROM: "monitor@drivendigital.us"
      MONITOR_JOB_BROKER: "redis://redis:6379"
      MONITOR_JOB_STORE: "redis://redis:6379"
      MONITOR_SMTP_HOST: "email-smtp.us-west-2.amazonaws.com"
      MONITOR_MESSAGE_QUEUE: "redis:6379"
    volumes:
      - ./data:/root/data
      - ./dist:/root/dist
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - monitor
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitor
    volumes:
      - monitor-postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    restart: always
    networks:
      - monitor

volumes:
  monitor-postgres:
    external: false

networks:
  monitor:
    driver: bridge
