# GraphQL schema example
#
# https://gqlgen.com/getting-started/
scalar UUID
type Install {
  ID: UUID!
  nicename: String!
  username: String!
  hostname: String!
  port: Int!
}

type Query {
  installs: [Install!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Install!
}
